Repository 1024pix/pix-tutos, pull requests merged in 2022-09, with the labels that each got.

#69 [FEATURE] Déplacement des tutos Pix+Edu dans `/edu`
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.json
  content/edu/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.json
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.json
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.json
  content/edu/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.json
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.json
  content/edu/connaitre-des-outils-de-quiz-en-ligne.json
  content/edu/identifier-des-sources-de-veille-incontournables.json
  content/edu/la-classe-inversee.json
  content/edu/le-cyberharcelement.json
  content/edu/le-droit-a-l-image-des-eleves.json
  content/edu/le-droit-d-auteur-des-eleves.json
  content/edu/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.json
  content/edu/le-principe-de-l-exception-pedagogique.json
  content/edu/le-rgpd-en-milieu-scolaire.json
  content/edu/le-site-cap-ecole-inclusive.json
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.json
  content/edu/les-acteurs-de-la-formation-en-ligne-des-enseignants.json
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.json
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.json
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.json
  content/edu/les-lieux-d-echange-en-ligne-entre-professionnels.json
  content/edu/les-referents-numeriques-pour-le-second-degre.json
  content/edu/les-systemes-robotises-de-telepresence.json
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.json
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.json
  content/edu/outils-pour-rendre-un-document-accessible.json
  content/edu/reperer-une-copie-ayant-eu-recours-au-plagiat.json
  content/edu/savoir-indexer-une-ressource-en-ligne-pour-la-partager.json
  content/edu/scenariser-une-capsule-video.json
  content/edu/se-connecter-a-sa-messagerie-academique.json
  content/edu/sites-ressources-pour-l-ecole-inclusive.json
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.json
  content/edu/utiliser-des-capsules-video-en-classe.json
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.json
  content/edu/utiliser-les-reseaux-sociaux-comme-outils-de-veille-informationnelle.json
  content/edu/utiliser-un-tni.json
  content/edu/utiliser-une-illustration-en-licence-libre.json
  layouts/edu.vue
  nuxt.config.js
  pages/edu/_slug.vue
  pages/edu/index.vue
  pages/index.vue
  tests/verify-edu-content.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-evaluation

#70 Ajout et remplissage du champ "area" sur tous les .json des tutos edu
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.json
  content/edu/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.json
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.json
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.json
  content/edu/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.json
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.json
  content/edu/connaitre-des-outils-de-quiz-en-ligne.json
  content/edu/identifier-des-sources-de-veille-incontournables.json
  content/edu/la-classe-inversee.json
  content/edu/le-cyberharcelement.json
  content/edu/le-droit-a-l-image-des-eleves.json
  content/edu/le-droit-d-auteur-des-eleves.json
  content/edu/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.json
  content/edu/le-principe-de-l-exception-pedagogique.json
  content/edu/le-rgpd-en-milieu-scolaire.json
  content/edu/le-site-cap-ecole-inclusive.json
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.json
  content/edu/les-acteurs-de-la-formation-en-ligne-des-enseignants.json
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.json
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.json
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.json
  content/edu/les-lieux-d-echange-en-ligne-entre-professionnels.json
  content/edu/les-referents-numeriques-pour-le-second-degre.json
  content/edu/les-systemes-robotises-de-telepresence.json
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.json
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.json
  content/edu/outils-pour-rendre-un-document-accessible.json
  content/edu/reperer-une-copie-ayant-eu-recours-au-plagiat.json
  content/edu/savoir-indexer-une-ressource-en-ligne-pour-la-partager.json
  content/edu/scenariser-une-capsule-video.json
  content/edu/se-connecter-a-sa-messagerie-academique.json
  content/edu/sites-ressources-pour-l-ecole-inclusive.json
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.json
  content/edu/utiliser-des-capsules-video-en-classe.json
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.json
  content/edu/utiliser-les-reseaux-sociaux-comme-outils-de-veille-informationnelle.json
  content/edu/utiliser-un-tni.json
  content/edu/utiliser-une-illustration-en-licence-libre.json
  tests/verify-edu-content.test.js
Labels: :rocket: Ready to Merge

#71 [FEATURE] Intégration page d'accueil Pix+Édu (PIX-5631)
  .babelrc
  assets/scss/globals.scss
  components/PixTutorial.vue
  components/PixTypography.vue
  pages/edu/_slug.vue
  pages/edu/index.vue
  pages/index.vue
  services/get-areas.js
  tests/verify-edu-content.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-evaluation

#72 [FEATURE] Customiser le lecteur vidéo (PIX-5659).
  components/PixTutorial.vue
  pages/edu/_slug.vue
  services/customizing-embed-video.js
  tests/services/customizing-embed-video.test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#73 [FEATURE] Amélioration libellés page d'accueil Pix+Édu
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, Func Review OK

#74 [FEATURE] Ajustements lien retour à la liste + libellé (PIX-5676)
  pages/edu/_slug.vue
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-evaluation
