Repository 1024pix/pix-tutos, pull requests merged in 2022-08, with the labels that each got.

#26 [FEATURE] Ajouter le contexte Pix+Édu dans le titre de la page d'un tuto
  nuxt.config.js
  pages/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-evaluation

#27 [FEATURE] Ajout de tests pour valider le contenu (PIX-5512)
  .circleci/config.yml
  .eslintrc.js
  content/la-certification.json
  content/les-tutos.json
  jest.config.js
  package-lock.json
  package.json
  tests/verify-content.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#30 Ajout tuto "Se connecter à sa messagerie académique"
  content/la-certification.json
  content/se-connecter-a-sa-messagerie-academique.json
Labels: :rocket: Ready to Merge

#31 Create configurer-son-client-de-messagerie-pour-recevoir-ses-mails-ac…
  content/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.json
Labels: :rocket: Ready to Merge

#32 Create communiquer-par-voie-numerique-aupres-de-la-communaute-educati…
  content/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.json
Labels: :rocket: Ready to Merge

#33 Nouveau tuto (4) : Communiquer efficacement par différents canaux auprès de ses élèves
  content/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.json
Labels: :rocket: Ready to Merge

#34 Nouveau tuto (5) : Les référents numériques pour le second degré
  content/les-referents-numeriques-pour-le-second-degre.json
Labels: :rocket: Ready to Merge

#35 Nouveau tuto (6) : Les acteurs institutionnels du numérique éducatif dans le 2nd degré
  content/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.json
Labels: :rocket: Ready to Merge

#36 Nouveau tuto (7) : Les lieux d'échange en ligne entre professionnels
  content/les-lieux-d-echange-en-ligne-entre-professionnels.json
Labels: :rocket: Ready to Merge

#37 Nouveau tuto (8) : Utiliser les réseaux sociaux comme outils de veille informationnelle
  content/utiliser-les-reseaux-sociaux-comme-outils-de-veille-informationnelle.json
Labels: :rocket: Ready to Merge

#38 Nouveau tuto (9) : Identifier des sources de veille incontournables
  content/identifier-des-sources-de-veille-incontournables.json
Labels: :rocket: Ready to Merge

#39 Nouveau tuto (10) : Les acteurs de la formation en ligne des enseignants
  content/les-acteurs-de-la-formation-en-ligne-des-enseignants.json
Labels: :rocket: Ready to Merge

#40 Nouveau tuto (11) : Les données à caractère personnel en milieu scolaire
  content/les-donnees-a-caractere-personnel-en-milieu-scolaire.json
Labels: :rocket: Ready to Merge

#42 Nouveau tuto (12) : Le RGPD en milieu scolaire
  content/le-rgpd-en-milieu-scolaire.json
Labels: :rocket: Ready to Merge

#43 Nouveau tuto (14) : Le cyberharcèlement
  content/le-cyberharcelement.json
Labels: :rocket: Ready to Merge

#44 Nouveau tuto (15) : Le modèle SAMR pour intégrer le numérique dans la pédagogie
  content/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.json
Labels: :rocket: Ready to Merge

#45 Nouveau tuto (16) : Suivre les avancées de la recherche sur le numérique éducatif
  content/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.json
Labels: :rocket: Ready to Merge

#47 Nouveau tuto (18) : Appliquer l'exception pédagogique et les exceptions aux droits d'auteur
  content/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.json
Labels: :rocket: Ready to Merge

#48 Nouveau tuto (19) : Utiliser une illustration en licence libre
  content/utiliser-une-illustration-en-licence-libre.json
Labels: :rocket: Ready to Merge

#50 Nouveau tuto (21) : Le droit d'auteur des élèves
  content/le-droit-d-auteur-des-eleves.json
Labels: :rocket: Ready to Merge

#52 Nouveau tuto (23) : Méthodes et outils pour concevoir une capsule vidéo
  content/methodes-et-outils-pour-concevoir-une-capsule-video.json
Labels: :rocket: Ready to Merge

#54 Nouveau tuto (25) : Utiliser des capsules vidéo en classe
  content/utiliser-des-capsules-video-en-classe.json
Labels: :rocket: Ready to Merge

#55 Create scenariser-une-capsule-video.json
  content/scenariser-une-capsule-video.json
Labels: :rocket: Ready to Merge

#56 Nouveau tuto (27) : La classe inversée
  content/la-classe-inversee.json
Labels: :rocket: Ready to Merge

#57 Nouveau tuto (28) : Utiliser un TBI/TNI
  content/utiliser_un_tni.json
Labels: :rocket: Ready to Merge

#59 Nouveau tuto (30) : Connaître des outils de quiz en ligne
  content/connaitre-des-outils-de-quiz-en-ligne.json
Labels: :rocket: Ready to Merge

#61 Nouveau tuto (32) : Les fonctionnalités de rétroaction des outils de quiz en ligne
  content/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.json
Labels: :rocket: Ready to Merge

#63 Nouveau tuto (34) : Repérer une copie ayant eu recours au plagiat
  content/reperer-une-copie-ayant-eu-recours-au-plagiat.json
Labels: :rocket: Ready to Merge

#62 Nouveau tuto (33) : Learning analytics et intelligence artificielle dans l'éducation
  content/learning-analytics-et-intelligence-artificielle-dans-l-education.json
Labels: :rocket: Ready to Merge

#46 Nouveau tuto (17) : Le principe de l'exception pédagogique
  content/le-principe-de-l-exception-pedagogique.json
Labels: :rocket: Ready to Merge

#49 Nouveau tuto (20) : Comprendre les Creative Commons pour une utilisation pédagogique
  content/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.json
Labels: :rocket: Ready to Merge

#64 Nouveau tuto (35) : Sites ressources pour l'école inclusive
  content/sites-ressources-pour-l-ecole-inclusive.json
Labels: :rocket: Ready to Merge

#60 Nouveau tuto (31) : Utiliser les outils de quiz en ligne pour diversifier son évaluation
  content/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.json
Labels: :rocket: Ready to Merge

#58 Nouveau tuto (29) : Connaître des applications à vidéoprojeter pour animer et gérer sa classe
  content/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.json
Labels: :rocket: Ready to Merge

#65 Nouveau tuto (36) : Outils pour rendre un document accessible
  content/outils-pour-rendre-un-document-accessible.json
Labels: :rocket: Ready to Merge

#67 Nouveau tuto (38) : Les systèmes robotisés de téléprésence
  content/les-systemes-robotises-de-telepresence.json
Labels: :rocket: Ready to Merge
