Repository 1024pix/pix-tutos, pull requests merged in 2022-06, with the labels that each got.

#3 [TECH] Ajout de la github action automerge (PIX-5029).
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge

#9 [TECH] Use Nuxt 2 (PIX-5067)
  app.vue
  nginx.conf
  nuxt.config.ts
  package-lock.json
  package.json
  pages/index.vue
  tsconfig.json
Labels: :rocket: Ready to Merge

#10 [TECH] Ajout du module Nuxt Content (PIX-5032).
  content/la-certification.json
  content/les-tutos.json
  nuxt.config.js
  package-lock.json
  package.json
  pages/_slug.vue
  pages/index.vue
Labels: :rocket: Ready to Merge

#11 [TECH]: Ajouter Prettier et Eslint (PIX-5073).
  .eslintrc.js
  .gitignore
  .prettierrc.json
  TUTOS.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/_slug.vue
  pages/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK

#14 [TECH] Ajout du template pour les Pull Requests.
  .github/pull_request_template.md
Labels: :rocket: Ready to Merge

#13 [BUGFIX] Accéder à un tutoriel sans devoir passer par la page d'accueil.
  .gitignore
  README.md
  docker-compose.yml
  nginx.conf
  servers.conf.erb
Labels: :rocket: Ready to Merge

#12 [FEATURE] Intégration de la page tutoriel (PIX-4981).
  assets/fonts/Open_Sans/italic-400.woff2
  assets/fonts/Open_Sans/normal-300.woff2
  assets/fonts/Open_Sans/normal-400.woff2
  assets/fonts/Open_Sans/normal-600.woff2
  assets/fonts/Open_Sans/normal-700.woff2
  assets/fonts/Roboto/normal-400.woff2
  assets/fonts/Roboto/normal-500.woff2
  assets/images/marianne-logo.svg
  assets/images/pix-logo.svg
  assets/scss/globals.scss
  assets/scss/globals/_google-font.scss
  components/PixButtonLink.vue
  components/PixTutorial.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/_slug.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK

#17 [TECH] Nettoyage et SR
  .node-version
  TUTOS.js
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK

#18 [TECH] Ajouter les commentaires avec le lien de la Review App (PIX-5134).
  package-lock.json
  package.json
  scripts/jira/comment-with-review-app-url.js
  scripts/signal_deploy_to_pr.sh
Labels: :rocket: Ready to Merge, Tech Review OK

#19 [TECH] Pouvoir activer l'indexation grâce à une variable d'environnement (PIX-5142).
  nuxt.config.js
  services/is-seo-indexing-enabled.js
Labels: :rocket: Ready to Merge, Tech Review OK

#15 [FEATURE] Ajout d'une page 404 custom (PIX-5074).
  layouts/error.vue
  layouts/simple.vue
  nuxt.config.js
  servers.conf.erb
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK

#20 [BUGFIX] La hauteur de la vidéo d'un tutoriel ne doit pas être trop grande
  components/PixTutorial.vue
  layouts/default.vue
  layouts/error.vue
  layouts/simple.vue
  nuxt.config.js
  pages/_slug.vue
  services/is-seo-indexing-enabled.js
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK

#21 [TECH] Ajout du linter dans le CI
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech Review OK

#16 [FEATURE] Ajoute les boutons de connection et d'inscription si absence de query string `?c` (PIX-5119)
  components/PixHeader.vue
  layouts/default.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK

#22 [TECH] Ajouter Fontsource (PIX-5100)
  assets/scss/fonts/open-sans.scss
  assets/scss/fonts/roboto.scss
  assets/scss/globals.scss
  assets/scss/globals/_google-font.scss
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK

#23 [FEATURE] Ajouter Matomo Tag Manager comme suivie d'audience (PIX-5328).
  config/environment.js
  nuxt.config.js
  static/scripts/start-matomo-event.js
Labels: :rocket: Ready to Merge, Tech Review OK

#24 [TECH] Ajoute un saut de ligne dans le commentaire Jira (PIX-5243)
  scripts/jira/comment-with-review-app-url.js
Labels: :rocket: Ready to Merge, Tech Review OK

#25 [BUGFIX] Ajouter le script Matomo Tag Manager
  nuxt.config.js
Labels: :rocket: Ready to Merge, Tech Review OK
