Repository 1024pix/pix-tutos, pull requests merged in 2023-10, with the labels that each got.

#231 [BUGFIX] Cache le lecteur vidéo de la MedNum dans les styles d'impression (PIX-9460)
  assets/scss/globals.scss
  layouts/mednum.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp

#232 [BUGFIX] Supprimer la marge de 8px autour du site (PIX-9468)
  assets/scss/globals.scss
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-chromium-darwin.png
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-chromium-linux.png
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-firefox-darwin.png
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-firefox-linux.png
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-webkit-darwin.png
  tests/e2e/edu/visual.spec.ts-snapshots/-edu-content-should-show-correctly-1-webkit-linux.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-chromium-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-chromium-linux.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-firefox-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-firefox-linux.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-webkit-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-webkit-linux.png
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp

#230 [TECH] Corriger la config ESLint (PIX-9462)
  .eslintrc.js
  config/environment.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-devcomp

#233 [BUGFIX] Centrer le lecteur vidéo MedNum en plein écran sur mobile (PIX-9469)
  package.json
  pages/mednum/[slug].vue
Labels: :rocket: Ready to Merge, Func Review OK, team-devcomp

#235 Correction coquille sur tuto +Edu (les-donnees-a-caractere-personnel-en-milieu-scolaire.md)
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.md
Labels: :rocket: Ready to Merge

#237 [BUGFIX] Remplacer le PDF `impact_environnemental` par la version avec les méta-données corrigées
  public/pdf/mednum/impact_environnemental.pdf
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp
