Repository 1024pix/pix-tutos, pull requests merged in 2023-09, with the labels that each got.

#204 Tutos +Edu : màj transcription domaines 2,3 et 4
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.md
  content/edu/comprendre-comment-differencier-grace-au-numerique.md
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.md
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.md
  content/edu/connaitre-des-supports-educatifs-ludiques-numeriques.md
  content/edu/la-classe-inversee.md
  content/edu/le-droit-d-auteur-des-eleves.md
  content/edu/le-principe-de-l-exception-pedagogique.md
  content/edu/le-site-cap-ecole-inclusive.md
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.md
  content/edu/les-banques-de-ressources-pedagogiques-en-ligne.md
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.md
  content/edu/les-systemes-robotises-de-telepresence.md
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.md
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.md
  content/edu/mettre-a-disposition-et-partager-des-ressources-a-des-pairs-2nd-degre.md
  content/edu/outils-pour-rendre-un-document-accessible.md
  content/edu/scenariser-une-capsule-video.md
  content/edu/sites-ressources-pour-l-ecole-inclusive.md
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.md
  content/edu/utiliser-des-capsules-video-en-classe.md
  content/edu/utiliser-et-creer-des-supports-educatifs-ludiques-numeriques.md
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.md
  content/edu/utiliser-un-tni.md
  content/edu/utiliser-une-illustration-en-licence-libre.md
Labels: :rocket: Ready to Merge

#205 [FEATURE] Ajout des tutos PDF pour la MedNum (PIX-8356)
  components/PixPdf.vue
  components/PixTutorial.vue
  content/mednum/icone-de-la-messagerie.md
  content/mednum/impact-environnemental.md
  content/mednum/interagir-avec-une-visualisation.md
  content/mednum/parametrer-une-dataviz.md
  content/mednum/quelle-adresse-mail-choisir.md
  content/mednum/trier-des-donnees.md
  content/mednum/un-pseudo-pourquoi-faire.md
  package-lock.json
  pages/edu/[slug].vue
  pages/mednum/[slug].vue
  public/pdf/mednum/icone_de_la_messagerie.pdf
  public/pdf/mednum/impact_environnemental.pdf
  public/pdf/mednum/quelle_adresse_mail_choisir.pdf
  tests/unit/verify-mednum-content.test.js
Labels: :rocket: Ready to Merge, team-devcomp

#210 Tuto Pix +Edu Mise à jour de 2 transcription
  content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md
  content/edu/ameliorer-la-cybersecurite-de-ses-outils-numeriques.md
Labels: :rocket: Ready to Merge

#213 MàJ 9 transcription vidéo domaine 5 +Edu
  content/edu/les-femmes-dans-les-metiers-du-numerique.md
  content/edu/les-impacts-ecologiques-du-numerique.md
  content/edu/les-modeles-economiques-du-numerique.md
  content/edu/les-outils-numeriques-pour-repenser-ses-pratiques-pedagogiques.md
  content/edu/mener-activites-et-projets-pour-travailler-le-crcn-avec-ses-eleves.md
  content/edu/preparer-une-seance-utilisant-des-outils-numeriques.md
  content/edu/recherche-sur-internet-bulles-de-filtres-et-desinformation.md
Labels: :rocket: Ready to Merge

#214 [FEATURE] Permettre le clic droit sur les vidéos Plyr (PIX-9157)
  assets/scss/globals.scss
  components/PixVideoPlayer.vue
Labels: :rocket: Ready to Merge, team-devcomp

#218 [FEATURE] Ajout de la traduction française pour le player vidéo de MedNum (PIX-9226)
  assets/translation/player_fr.js
  components/PixVideoPlayer.vue
Labels: :rocket: Ready to Merge, team-devcomp

#217 MàJ description tutos MedNum
  content/mednum/icone-de-la-messagerie.md
  content/mednum/impact-environnemental.md
  content/mednum/interagir-avec-une-visualisation.md
  content/mednum/parametrer-une-dataviz.md
  content/mednum/quelle-adresse-mail-choisir.md
  content/mednum/trier-des-donnees.md
  content/mednum/un-pseudo-pourquoi-faire.md
Labels: :rocket: Ready to Merge

#219 [FEATURE] Ajouter la description sur la page d'accueil de la mednum (PIX-9305)
  pages/mednum/index.vue
  tests/e2e/mednum/content.spec.ts
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp

#221 [BUGFIX] Page MedNum - modifier le label du CTA pour les PDF (PIX-9300)
  components/PixPdf.vue
Labels: :rocket: Ready to Merge, Func Review OK, team-devcomp

#222 [BUGFIX] Coquille à corriger dans la description de l'accueil de Mednum (PIX-9305)
  pages/mednum/index.vue
Labels: :rocket: Ready to Merge, Func Review OK, team-devcomp

#220 MàJ transcription tutos vidéos MedNum
  content/mednum/interagir-avec-une-visualisation.md
  content/mednum/parametrer-une-dataviz.md
  content/mednum/trier-des-donnees.md
  content/mednum/un-pseudo-pourquoi-faire.md
Labels: :rocket: Ready to Merge

#226 Revert "[BUMP] Update dependency node to v18.18.0"
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge

#223 [TECH] Ajout d'un test de non régression visuelle sur la homepage de la MedNum (PIX-9306)
  package.json
  tests/e2e/mednum/visual.spec.ts
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-chromium-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-chromium-linux.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-firefox-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-firefox-linux.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-webkit-darwin.png
  tests/e2e/mednum/visual.spec.ts-snapshots/-mednum-content-should-show-correctly-1-webkit-linux.png
Labels: :rocket: Ready to Merge, Tech Review OK, team-devcomp

#207 [TECH] Linter les fichiers markdown du dossier `content` (PIX-9457)
  content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md
  content/edu/ameliorer-la-cybersecurite-de-ses-outils-numeriques.md
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.md
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.md
  content/edu/comprendre-comment-differencier-grace-au-numerique.md
  content/edu/connaitre-des-supports-educatifs-ludiques-numeriques.md
  content/edu/connaitre-les-regles-d-edition-pour-rendre-plus-accessible-des-ressources.md
  content/edu/l-histoire-du-numerique-a-l-ecole.md
  content/edu/la-classe-inversee.md
  content/edu/le-droit-d-auteur-des-eleves.md
  content/edu/le-site-cap-ecole-inclusive.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-1er-degre.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.md
  content/edu/les-banques-de-ressources-pedagogiques-en-ligne.md
  content/edu/les-erun-acteurs-du-numerique-educatif.md
  content/edu/les-groupes-thematiques-numeriques-gtnum.md
  content/edu/les-lieux-d-echange-en-ligne-entre-professionnels.md
  content/edu/les-outils-numeriques-pour-repenser-ses-pratiques-pedagogiques.md
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.md
  content/edu/mettre-a-disposition-et-partager-des-ressources-a-des-pairs-2nd-degre.md
  content/edu/outils-pour-differencier-grace-au-numerique.md
  content/edu/realite-augmentee-et-realite-virtuelle-au-service-des-apprentissages.md
  content/edu/se-connecter-a-sa-messagerie-academique.md
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.md
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.md
  content/edu/utiliser-des-capsules-video-en-classe.md
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.md
  content/mednum/trier-des-donnees.md
  package.json
  pages/mednum/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-devcomp
