Repository 1024pix/pix-tutos, pull requests merged in 2023-06, with the labels that each got.

#152 [TECH] Utiliser les nouveautés de Nuxt3 et de Vue3 (PIX-8163).
  layouts/edu.vue
  layouts/simple.vue
  pages/edu/[slug].vue
  pages/edu/index.vue
  pages/index.vue
Labels: :rocket: Ready to Merge, team-devcomp

#153 Ajout scripts 41 tutos Canopé
  content/edu/agir-face-au-cyberharcelement.md
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.md
  content/edu/cadre-et-acteurs-du-rgpd-en-milieu-scolaire.md
  content/edu/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.md
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.md
  content/edu/comprendre-comment-differencier-grace-au-numerique.md
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.md
  content/edu/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.md
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.md
  content/edu/connaitre-des-outils-de-quiz-en-ligne.md
  content/edu/identifier-des-sources-de-veille-incontournables.md
  content/edu/la-classe-inversee.md
  content/edu/le-cadre-de-reference-des-competences-numeriques.md
  content/edu/le-cahier-de-texte-numerique.md
  content/edu/le-cyberharcelement.md
  content/edu/le-droit-a-l-image-des-eleves.md
  content/edu/le-droit-d-auteur-des-eleves.md
  content/edu/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-modele-tpack-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-principe-de-l-exception-pedagogique.md
  content/edu/le-rgpd-en-milieu-scolaire.md
  content/edu/le-site-cap-ecole-inclusive.md
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.md
  content/edu/les-acteurs-de-la-formation-en-ligne-des-enseignants.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.md
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.md
  content/edu/les-erun-acteurs-du-numerique-educatif.md
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.md
  content/edu/les-referents-numeriques-pour-le-second-degre.md
  content/edu/les-systemes-robotises-de-telepresence.md
  content/edu/les-travaux-academiques-mutualises.md
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.md
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.md
  content/edu/mettre-en-place-une-strategie-de-veille.md
  content/edu/outils-pour-rendre-un-document-accessible.md
  content/edu/partager-et-diffuser-sa-veille-informationnelle.md
  content/edu/reperer-une-copie-ayant-eu-recours-au-plagiat.md
  content/edu/resoudre-des-problemes-simples-lies-aux-outils-numeriques.md
  content/edu/savoir-indexer-une-ressource-en-ligne-pour-la-partager.md
  content/edu/scenariser-une-capsule-video.md
  content/edu/se-connecter-a-sa-messagerie-academique.md
  content/edu/sites-ressources-pour-l-ecole-inclusive.md
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.md
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.md
  content/edu/utiliser-des-capsules-video-en-classe.md
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.md
  content/edu/utiliser-un-tni.md
  content/edu/utiliser-une-illustration-en-licence-libre.md
Labels: :rocket: Ready to Merge

#154 [FEATURE] Ajouter un bouton de téléchargement du transcript (PIX-8151).
  assets/scss/globals.scss
  components/PixButton.vue
  components/PixTutorial.vue
  layouts/edu.vue
Labels: :rocket: Ready to Merge, team-devcomp

#156 [FEATURE] Ajoute les logos de partenaires en fin des pages Edu + renommer 'script'/'transcript' en 'transcription' (PIX-8256)
  components/PixTutorial.vue
  content/edu/agir-face-au-cyberharcelement.md
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.md
  content/edu/cadre-et-acteurs-du-rgpd-en-milieu-scolaire.md
  content/edu/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.md
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.md
  content/edu/comprendre-comment-differencier-grace-au-numerique.md
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.md
  content/edu/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.md
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.md
  content/edu/connaitre-des-outils-de-quiz-en-ligne.md
  content/edu/identifier-des-sources-de-veille-incontournables.md
  content/edu/la-classe-inversee.md
  content/edu/le-cadre-de-reference-des-competences-numeriques.md
  content/edu/le-cahier-de-texte-numerique.md
  content/edu/le-cyberharcelement.md
  content/edu/le-droit-a-l-image-des-eleves.md
  content/edu/le-droit-d-auteur-des-eleves.md
  content/edu/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-modele-tpack-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-principe-de-l-exception-pedagogique.md
  content/edu/le-rgpd-en-milieu-scolaire.md
  content/edu/le-site-cap-ecole-inclusive.md
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.md
  content/edu/les-acteurs-de-la-formation-en-ligne-des-enseignants.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.md
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.md
  content/edu/les-erun-acteurs-du-numerique-educatif.md
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.md
  content/edu/les-referents-numeriques-pour-le-second-degre.md
  content/edu/les-systemes-robotises-de-telepresence.md
  content/edu/les-travaux-academiques-mutualises.md
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.md
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.md
  content/edu/mettre-en-place-une-strategie-de-veille.md
  content/edu/outils-pour-rendre-un-document-accessible.md
  content/edu/partager-et-diffuser-sa-veille-informationnelle.md
  content/edu/reperer-une-copie-ayant-eu-recours-au-plagiat.md
  content/edu/resoudre-des-problemes-simples-lies-aux-outils-numeriques.md
  content/edu/savoir-indexer-une-ressource-en-ligne-pour-la-partager.md
  content/edu/scenariser-une-capsule-video.md
  content/edu/se-connecter-a-sa-messagerie-academique.md
  content/edu/sites-ressources-pour-l-ecole-inclusive.md
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.md
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.md
  content/edu/utiliser-des-capsules-video-en-classe.md
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.md
  content/edu/utiliser-un-tni.md
  content/edu/utiliser-une-illustration-en-licence-libre.md
  layouts/edu.vue
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp

#161 [FEATURE] A l'impression, ajouter le logo de Pix
  layouts/edu.vue
Labels: :rocket: Ready to Merge, team-devcomp

#162 [BUGFIX] Rétablir Matomo
  nuxt.config.ts
Labels: :rocket: Ready to Merge, team-devcomp

#163 [BREAKING] Ajoute des `id` aux boutons d'action pour Matomo
  components/PixTutorial.vue
  content/edu/agir-face-au-cyberharcelement.md
  content/edu/appliquer-l-exception-pedagogique-et-les-exceptions-aux-droits-d-auteur.md
  content/edu/cadre-et-acteurs-du-rgpd-en-milieu-scolaire.md
  content/edu/communiquer-efficacement-par-differents-canaux-aupres-de-ses-eleves.md
  content/edu/communiquer-par-voie-numerique-aupres-de-la-communaute-educative.md
  content/edu/comprendre-comment-differencier-grace-au-numerique.md
  content/edu/comprendre-les-creative-commons-pour-une-utilisation-pedagogique.md
  content/edu/configurer-son-client-de-messagerie-pour-recevoir-ses-mails-academiques.md
  content/edu/connaitre-des-applications-a-videoprojeter-pour-animer-et-gerer-sa-classe.md
  content/edu/connaitre-des-outils-de-quiz-en-ligne.md
  content/edu/identifier-des-sources-de-veille-incontournables.md
  content/edu/la-classe-inversee.md
  content/edu/le-cadre-de-reference-des-competences-numeriques.md
  content/edu/le-cahier-de-texte-numerique.md
  content/edu/le-cyberharcelement.md
  content/edu/le-droit-a-l-image-des-eleves.md
  content/edu/le-droit-d-auteur-des-eleves.md
  content/edu/le-modele-samr-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-modele-tpack-pour-integrer-le-numerique-dans-la-pedagogie.md
  content/edu/le-principe-de-l-exception-pedagogique.md
  content/edu/le-rgpd-en-milieu-scolaire.md
  content/edu/le-site-cap-ecole-inclusive.md
  content/edu/learning-analytics-et-intelligence-artificielle-dans-l-education.md
  content/edu/les-acteurs-de-la-formation-en-ligne-des-enseignants.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-2nd-degre.md
  content/edu/les-donnees-a-caractere-personnel-en-milieu-scolaire.md
  content/edu/les-erun-acteurs-du-numerique-educatif.md
  content/edu/les-fonctionnalites-de-retroaction-des-outils-de-quiz-en-ligne.md
  content/edu/les-lieux-d-echange-en-ligne-entre-professionnels.md
  content/edu/les-referents-numeriques-pour-le-second-degre.md
  content/edu/les-systemes-robotises-de-telepresence.md
  content/edu/les-travaux-academiques-mutualises.md
  content/edu/methodes-et-outils-pour-concevoir-une-capsule-video.md
  content/edu/methodes-et-outils-pour-le-montage-d-une-capsule-video.md
  content/edu/mettre-en-place-une-strategie-de-veille.md
  content/edu/outils-pour-rendre-un-document-accessible.md
  content/edu/partager-et-diffuser-sa-veille-informationnelle.md
  content/edu/reperer-une-copie-ayant-eu-recours-au-plagiat.md
  content/edu/resoudre-des-problemes-simples-lies-aux-outils-numeriques.md
  content/edu/savoir-indexer-une-ressource-en-ligne-pour-la-partager.md
  content/edu/scenariser-une-capsule-video.md
  content/edu/se-connecter-a-sa-messagerie-academique.md
  content/edu/sites-ressources-pour-l-ecole-inclusive.md
  content/edu/suivre-les-avancees-de-la-recherche-sur-le-numerique-educatif.md
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.md
  content/edu/utiliser-des-capsules-video-en-classe.md
  content/edu/utiliser-les-outils-de-quiz-en-ligne-pour-diversifier-son-evaluation.md
  content/edu/utiliser-les-reseaux-sociaux-comme-outils-de-veille-informationnelle.md
  content/edu/utiliser-un-tni.md
  content/edu/utiliser-une-illustration-en-licence-libre.md
  pages/edu/[slug].vue
  tests/unit/verify-edu-content.test.js
Labels: :rocket: Ready to Merge, team-devcomp

#167 Création nouvelles pages tutos Pix
  content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md
  content/edu/ameliorer-la-cybersecurite-de-ses-outils-numeriques.md
  content/edu/connaitre-des-supports-educatifs-ludiques-numeriques.md
  content/edu/connaitre-les-regles-d-edition-pour-rendre-plus-accessible-des-ressources.md
  content/edu/ecole-familles-et-numerique.md
  content/edu/eduquer-aux-donnees-pour-developper-des-communs.md
  content/edu/l-histoire-du-numerique-a-l-ecole.md
  content/edu/la-progression-des-eleves-dans-la-maitrise-du-crcn.md
  content/edu/le-bien-etre-numerique.md
  content/edu/le-suivi-des-competences-numeriques-tout-au-long-de-la-scolarite.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-1er-degre.md
  content/edu/les-banques-de-ressources-pedagogiques-en-ligne.md
  content/edu/les-femmes-dans-les-metiers-du-numerique.md
  content/edu/les-groupes-thematiques-numeriques-gtnum.md
  content/edu/les-impacts-ecologiques-du-numerique.md
  content/edu/les-modeles-economiques-du-numerique.md
  content/edu/mener-activites-et-projets-pour-travailler-le-crcn-avec-ses-eleves.md
  content/edu/mettre-a-disposition-et-partager-des-ressources-a-des-pairs-2nd-degre.md
  content/edu/outils-numeriques-en-etablissement-connaitre-son-environnement-de-travail.md
  content/edu/outils-pour-differencier-grace-au-numerique.md
  content/edu/preparer-une-seance-utilisant-des-outils-numeriques.md
  content/edu/realite-augmentee-et-realite-virtuelle-au-service-des-apprentissages.md
  content/edu/recherche-sur-internet-bulles-de-filtres-et-desinformation.md
  content/edu/une-breve-histoire-d-internet.md
  content/edu/utiliser-et-creer-des-supports-educatifs-ludiques-numeriques.md
Labels: :rocket: Ready to Merge

#168 [BUGFIX] Corriger l'ordre des domaines sur /edu
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, team-devcomp
