Repository 1024pix/pix-tutos, pull requests merged in 2023-05, with the labels that each got.

#130 [FEATURE] Ajouter les logos des partenaires au dessus du listing des tutos edu (PIX-7396)
  .gitignore
  assets/images/partners.png
  assets/scss/globals.scss
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-evaluation

#145 [BUGFIX] Rétablir l'ordre des domaines (PIX-8149).
  pages/edu/index.vue
Labels: :rocket: Ready to Merge, team-devcomp

#146 [BUGFIX] Supprimer le lien d'ancrage des transcripts (PIX-8156)
  nuxt.config.ts
Labels: :rocket: Ready to Merge, Func Review OK, team-devcomp

#147 [BUGFIX] Resserrer le bouton de téléchargement et le bloc vidéo (PIX-8155)
  components/PixTutorial.vue
Labels: :rocket: Ready to Merge, team-devcomp
