Repository 1024pix/pix-tutos, pull requests merged in 2023-11, with the labels that each got.

#251 [FEATURE] Ajouter des tutos vidéos pour les sixièmes (PIX-9958)
  components/PixVideoPlayer.vue
  content/sixieme/comment-reconnaitre-des-situations-de-cyberharcelement-et-comment-y-faire-face.md
  layouts/sixieme.vue
  pages/index.vue
  pages/sixieme/[slug].vue
  pages/sixieme/index.vue
  tests/e2e/sixieme/content.spec.ts
  tests/unit/verify-sixieme-content.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, Func Review OK, team-devcomp

#249 [FEATURE] Renommer des boutons d'action (PIX-9950) (PIX-9166)
  components/PixPdf.vue
  pages/edu/[slug].vue
  pages/mednum/[slug].vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-devcomp

#253 Correction page tuto identifier-des-situations-d-arnaque-par-manipulation-psychologique
  content/sixieme/identifier-des-situations-d-arnaque-par-manipulation-psychologique.md
Labels: :rocket: Ready to Merge

#254 Corrections titre vidéo
  content/sixieme/connaitre-et-utiliser-la-capacite-du-gps-et-d-une-adresse-ip-a-geolocaliser-un-appareil.md
  content/sixieme/connaitre-les-notions-de-donnees-a-caractere-personnel-de-recoupement-et-d-anonymisation.md
  content/sixieme/connaitre-les-recommandations-pour-le-choix-d-un-mot-de-passe-robuste.md
  content/sixieme/identifier-des-situations-d-arnaque-par-manipulation-psychologique.md
  content/sixieme/maitriser-l-acces-a-ses-donnees-lors-de-l-installation-d-une-application.md
Labels: :rocket: Ready to Merge
