Repository 1024pix/pix-tutos, pull requests merged in 2023-02, with the labels that each got.

#97 Ajout des descriptions courtes pour les nouveaux tutoriels Canopé
  content/edu/agir-face-au-cyberharcelement.json
  content/edu/cadre-et-acteurs-du-rgpd-en-milieu-scolaire.json
  content/edu/comprendre-comment-differencier-grace-au-numerique.json
  content/edu/le-cadre-de-reference-des-competences-numeriques.json
  content/edu/le-cahier-de-texte-numerique.json
  content/edu/le-modele-tpack-pour-integrer-le-numerique-dans-la-pedagogie.json
  content/edu/les-erun-acteurs-du-numerique-educatif.json
  content/edu/les-travaux-academiques-mutualises.json
  content/edu/partager-et-diffuser-sa-veille-informationnelle.json
  content/edu/resoudre-des-problemes-simples-lies-aux-outils-numeriques.json
  content/edu/trouver-et-proposer-des-ressources-pour-le-site-prim-a-bord.json
Labels: :rocket: Ready to Merge

#100 [TECH] Ajouter la config pour renovate
  .github/pull_request_template.md
  .github/renovate.json
Labels: :rocket: Ready to Merge, Tech Review OK

#116 [TECH] Ajouter des tests de non régressions
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/e2e/content.spec.ts.js
  tests/unit/services/customizing-embed-video.test.js
  tests/unit/verify-edu-content.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#122 Correctifs coquilles (titre / domaine)
  content/edu/comprendre-comment-differencier-grace-au-numerique.json
  content/edu/partager-et-diffuser-sa-veille-informationnelle.json
Labels: :rocket: Ready to Merge

#123 Création d'une page pour un nouveau tuto
  content/edu/mettre-en-place-une-strategie-de-veille.json
Labels: :rocket: Ready to Merge
