Repository 1024pix/pix-tutos, pull requests merged in 2024-08, with the labels that each got.

#347 [TECH] Regrouper les montées de version Node
  .circleci/config.yml
Labels: team-devcomp

#349 [TECH] Regrouper les montées de version Node
  .circleci/config.yml
Labels: team-devcomp

#332 [FEATURE] Ajout des transcriptions et des liens de téléchargement des webinaires
  content/edu/le-developpement-des-competences-numeriques-des-eleves.md
Labels: :rocket: Ready to Merge

#359 [FEATURE] Ajout de lien de téléchargement manquant
  content/edu/accompagner-les-eleves-a-la-maitrise-de-leur-identite-numerique.md
  content/edu/connaitre-des-supports-educatifs-ludiques-numeriques.md
  content/edu/eduquer-aux-donnees-pour-developper-des-communs.md
  content/edu/le-bien-etre-numerique.md
  content/edu/les-acteurs-institutionnels-du-numerique-educatif-dans-le-1er-degre.md
  content/edu/les-banques-de-ressources-pedagogiques-en-ligne.md
  content/edu/les-femmes-dans-les-metiers-du-numerique.md
  content/edu/les-groupes-thematiques-numeriques-gtnum.md
  content/edu/les-impacts-ecologiques-du-numerique.md
  content/edu/les-modeles-economiques-du-numerique.md
  content/edu/mettre-a-disposition-et-partager-des-ressources-a-des-pairs-2nd-degre.md
  content/edu/outils-pour-differencier-grace-au-numerique.md
  content/edu/realite-augmentee-et-realite-virtuelle-au-service-des-apprentissages.md
  content/edu/recherche-sur-internet-bulles-de-filtres-et-desinformation.md
  content/edu/utiliser-et-creer-des-supports-educatifs-ludiques-numeriques.md
  tests/unit/verify-edu-content.test.js
Labels: :rocket: Ready to Merge

#366 [TECH] Remplacer Jean Pierre par le bouton de merge natif
  .github/workflows/auto-merge.yml
Labels: cross-team

#369 [TECH] Met la GitHub Action de release au bon endroit
  .github/workflows/release.yaml
Labels: team-devcomp

#370 [TECH] Ajoute un checkout manquant dans l'action de release
  .github/workflows/release.yaml
Labels: team-devcomp
